### ISSUE TITLE
Query planning and execution

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#13]
For the Sept 2020 relay, we devised a question that looked like:
(asthma)-(chemical1)-(gene1)-(asthma), (gene1)-(gene2)-(chemical2)
So it's a triangle with one bound node, and a tail on one of the unbound nodes.

Current strider takes a long time, partly because it spends time going down the tail before ensuring that the (gene1) from which it is branching will satisfy the constraint of the original triangle.

So how could we think about putting in a query planning step and what would we do with the plan?

A typical query plan orders specific operations to produce a result.  They async nature of strider means that the implementation of the plan might be different, but if viewed in terms of which constraints must be satisfied in which order, then it might work.  For instance,  in the case above, we'd like to not go down the tail until we've found a gene that satisfies the triangle.

So one approach might be to break a query into a series of non-overlapping subqueries, with dependencies.  Each subquery is basically an independent strider queue, fed by its parent queries.    So there's a strider process handling the triangle.  As it finds genes that fully satisfy that query, it passes them to the next chunk, which can kick off the tail processing.  These can still occur async; the first doesn't need to fully complete, but it won't generate any work for the second until it finds at least one input that matches the whole first query.

As for how to do this decomposition, one approach would be something like - 
Find all paths between bound nodes (including loops beginning and ending at the same bound node).  Order these, short to long.   If there's overlaps at unbound nodes, those become dependencies from one subquery to another.

A second, cheaper?, approach would be to borrow somebody else's query planner.  Typically query planners would make use of count information to decide on which things to do first.  But in the federated landscape, we don't have that.  So imagine doing something like setting up a random neo4j graph, with arbitrarily assigned node labels.  Then feed the prospective query to cypher's planner and transform the result into a strider plan.

**Comment by patrickkwang** [comment]
Let me try to describe the current design of Strider and why this complexity is not generally reducible. We can and likely should make some approximations to reduce the computational load, but they will be lossy.

Imagine we have a KP ecosystem in which edges may only be found unidirectionally and independently. Each edge may be established subject-to-object or object-to-subject. That is, for edges of the form "disease affects gene", we may have one KP that provides these triples given a disease, and another that provides them given a gene. To find all such edges, we must therefore make one query for every disease in existence, _and_ one for every gene. Regardless of what else the disease and gene are connected to (even pinned nodes), we are required to query in both directions to obtain all results. That's one type of edge, and perhaps the most difficult. If we had a unidirectional edge that KPs only provide e.g. subject-to-object, we need only make a query for each candidate subject. The set of possible bindings for the object node is then constrained by that unidirectional connection. In general, the set of possible bindings for any node is constrained by the unidirectional connections to it. If all connections are bidirectional, then the entire population of such nodes must be considered.

Strider does not go to that extreme. It only expands from nodes that are a) pinned or b) result from a KP query. It does not repeat any specific KP call. But it will, upon receiving a new node, attempt to expand along all KP connections from that node. This is the "correct" behavior even in loop-and-tail queries because it could end up traversing back up the tail with some new nodes that satisfy the loop. _Unless_ the connection at the base of the tail is unidirectional and can only be established in the tail-ward direction. Strider makes the conservative assumption that all connections may be established bidirectionally, yielding the simple "always expand" policy.

If we took on the bookkeeping necessary to eliminate that assumption, that's a lossless optimization. I don't expect it to often make a difference given the huge number of KP connections from the Service Provider and Automat.

A lossy approximation we could make is the "no turn-arounds" rule in which we disallow traversing the same edge twice in sequence.

Neither of these fixes helps with infinite loops, so we could go ahead and disallow traversing the same query node twice, in any contiguous series of steps. That's lossy, for those keeping track.

But it doesn't necessarily fix @cbizon's issue with the loop-and-tail query because we can still explore the tail when the loop does not close, either because we traverse both simultaneously, or because we explore the tail first. If we somehow enforce that these are done in series, the heuristic approach you suggest could work.

My concerns with implementing these sorts of optimizations are mostly around the bookkeeping. We need to keep track of which query plan(s) and which result(s) are associated with any particular KP query or response, without repeating any.

All of this is complicated (and simplified?) if KP connections are not independent, i.e. if the same source of connections can be queried from either direction (subject-to-object or object-to-subject). This is the case with Plater KPs.

**Comment by cbizon** [comment]
Thanks for the details.

> Strider makes the conservative assumption that all connections may be established bidirectionally, yielding the simple "always expand" policy.

It strikes me that bi-directionality simplifies things immensely, because once you have been at a node, you never need to worry about coming back to it.  Unidirectionality means you can't make that assumption, and so you have to worry that e.g. you might find something in the tail that could close the loop.  But if you have bidirectionality, then you can know that just traversing the loop will find all possible closures of the loop. 

Is that right?

**Comment by cbizon** [comment]
The other thought I had about how to speed up this query would be to incorporate constraints into the likely score heuristic.  It might require a little modification, because I think the scores would need to be applied at an edge rather than a node level?

But either way, if a node is connected in two or more ways to bound nodes then going down branches to unbound nodes should be deprioritized until that node is in at least one successful path connecting to all the bound nodes it can be connected to.

**Comment by patrickkwang** [comment]
"Bidirectional" is a bit ambiguous here. It could mean a connection that can be queried from either direction _and produce the same results_. This is what Plater does, and it's good for us. But "bidirectional" could also mean a connection that can be queried from either direction and produce _different_ results. That's what e.g. Service Provider often does, and it's bad news. That's what leads to the tail traversals in the lossless scheme, because you could find yourself arriving back at the loop _with new knowledge_. We could call these "symmetrical" (good) and "asymmetrical" (bad)? I tried to use "bidirectional" only in the asymmetrical sense, and only mentioned the symmetric case at the end, because it's a minority of KPs that provide that.

**Comment by cbizon** [comment]
Yeah, that's gross.  

1. We should try to get KPs to make symmetric interfaces where we can
2. If we know which ones were symmetric, we could make smarter query plans
3. Even if we are in a morass where we're uncertain, we can still tilt towards returning answers quicker (in the async/streaming sense) by prioritizing the satisfaction of constraints

**Comment by cbizon** [comment]
One more thought - The idea that we need to backtrack to get all possible results because of asymmetric calls is correct.  On the other hand, I bet we get > 95% of paths back without it and more if we are hitting as many sources as we can.

So I'm wondering if we could think about 'quick' mode and 'thorough' mode.  The first would not do any backtracking. The second would be what we do now (but maybe starting from a quick version?)

**Comment by patrickkwang** [comment]
The latest Strider runs with a finite sequential plan, so should handle branching and looping more efficiently, if slightly less completely. Let's make more specific issues if/when they surface.
