### ISSUE TITLE
Implement attribute fetching

### ISSUE THREAD

**Issue by patrickkwang** [ranking-agent/strider#287]
When nodes have constraints, we can make zero-hop (annotate?) requests to KPs that have the proper attribute(s), before filtering.

**Comment by richakanwar13** [comment]
Issues with testing. Abrar working to resolve.

**Comment by uhbrar** [comment]
Based on some discussion, I'm concerned about the speed of this process. The only feasible and complete way that I can think of to actually get the attributes for a node n0 is to send a bunch of one-hop queries to KP's in the format of "n0 related_to named_thing". Unfortunately, just sending a query to a KP specifying a node and no edges results in an error. Therefore, we end up with a bunch of unnecessary and useless information which takes a long time to retrieve. I'm trying to think of a better way to do this, but I'm just stuck.

@cbizon @kennethmorton

**Comment by cbizon** [comment]
I also have some concerns re: speed here, but maybe this will help somewhat.    ARAs and KPs can implement different operations.   (See https://github.com/NCATSTranslator/OperationsAndWorkflows).    "lookup" is the default, but there is also [annotate nodes](https://github.com/NCATSTranslator/OperationsAndWorkflows/blob/main/operations/annotate_nodes.yml).

So you can send a message with a kgraph in it, and using the TRAPI "workflow" element ask for the annotate_nodes operation, and it will return that message with its node properties added in.

So that leaves the question of how you know where to send the message to collect the right node properties.   The original idea here was to try this out using automat's molepro-fda, which includes a single property defined in biolink.  But the way it will work in the future is that KP's will expose that they can do annotate_nodes in their smartapi schema just as ARAs do, and then their 'meta_knowledge_graph' endpoint will say what properties they can add.   

So to fully implement will also require some updates to the kp-registry to gather this info and make it queryable.

Does that help?

**Comment by uhbrar** [comment]
Yes, actually a lot. 

That last bit was something I was already working on, where the KP-registry would be able to provide a list of KP's that say that they list the constraint in question, similar to how the KP-registry already scans KP's for a suitable pattern when given a query. This allows us to hit only the KP's that actually have useful information, so we can limit our requests to only the KP's that list the constraint in their meta-knowledge graph and not make any unnecessary calls. No issues on that end, at least for now. 

One future issue that we might want to consider is that how we might resolve conflicting information, i.e. one KP says that a certain drug is FDA approved while another says that it isn't. As of now, I'm just going with the first result that I receive.

I was unaware that the KP's also used the workflow elements, which should be a great way to resolve this issue. I guess in that case, the KP-registry would have to also check the KP's to see which support the annotate_nodes operation?

**Comment by cbizon** [comment]
> I was unaware that the KP's also used the workflow elements, which should be a great way to resolve this issue. I guess in that case, the KP-registry would have to also check the KP's to see which support the annotate_nodes operation?

Right.  So I think e.g. all the automat KPs have this in their smartapi registrations:
```
"x-trapi": {
"operation": [
"lookup",
"overlay_connect_knodes",
"annotate_nodes"
],
"version": "1.2.0"
}
```

Unfortunately, I don't think that any of them expose which properties they have yet.  But maybe we can prioritize that...

**Comment by cbizon** [comment]
Though looking at that, I think it's actually invalid, it should say "operations" not "operation"

**Comment by maximusunc** [comment]
OBE. We haven't found this to be a need.
