### ISSUE TITLE
Implement qedge_keys parameter to fill?

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#337]
To discuss on 11/19

https://github.com/NCATSTranslator/OperationsAndWorkflows/pull/62

**Comment by cbizon** [comment]
This pull request relates to the fill operation (which strider doesn't implement) but might eventually bleed to lookup.  It allows you to send in a qgraph and say "just do this part of it".   Operations would like us to say whether this is going to be trouble for us or not.

**Comment by kennethmorton** [comment]
To document my thoughts now. If we wanted to support the fill operation or we wanted lookup to also support selective edge operation, I think we can handle this fairly simple in Aragorn rather than Strider. As strider essentially only does lookup and currently only full lookup. Aragorn should be responsible here as this is a workflow operation. My proposal is to pass a modified query to strider, who will then do a "full" lookup on the modified query. Aragorn can then put the pieces back together. 

This is a weakly held opinion.

**Comment by maximusunc** [comment]
OBE. This never happened.
