### ISSUE TITLE
No results for two hop?

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#353]
This query goes (hyperlipidemia)-(gene)-(small molecule), with related_tos for the edges.

For some reason, (dev) strider returns no results.   I can't see why not - searching robokopkg there should be plenty of such paths.

```
qq={
  "message": {
    "query_graph": {
      "nodes": {
        "n0": {
          "ids": ["MONDO:0021187"]
        },
        "n1": {
          "categories": [
            "biolink:Gene"
          ]
        },
        "n2": {
          "categories": [
            "biolink:SmallMolecule"
          ]
        }
      },
      "edges": {
        "e01": {
          "object": "n0",
          "subject": "n1",
          "predicates": ["biolink:related_to"]
        },
        "e02": {
          "subject":"n1",
          "object": "n2",
          "predicates": ["biolink:related_to"]
        }
      }
    }
  }
}
```

Maybe something is wrong with the query, but I don't see what, and I got results back for a different input ID (hypothyroidism)

**Comment by uhbrar** [comment]
I'm getting the same problem on my end, and I've been trying to figure out what's causing it. From what I can tell, at least on my end, this is because the KP-registry is empty when running the dev version of strider. Even when trying to use /refresh on the KP-registry, it still comes out empty. Since there are no KP's being loaded into the KP-registry, there are no KP's to provide results. 

@cbizon are you experiencing similar behavior?
