### ISSUE TITLE
affects_stability_of / CTD missing data

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#86]
This query:
```
{'message': {'query_graph': {'nodes': {'a': {'category': 'biolink:NamedThing', 'id': 'NCBIGENE:18671'}, 'b': {'category': 'biolink:ChemicalSubstance'}}, 'edges': {'ab': {'subject': 'a', 'object': 'b', 'predicate': 'biolink:affects_stability_of'}}}}}
```
works in automat/ctd, but not in strider.

**Comment by alongreyber** [comment]
There are a few issues with this query...

1. Right now automat/ctd does not advertise the exact operation that is in this query graph: `NamedThing-affects_stability_of->ChemicalSubstance`. It does advertise `Gene-affects_stability_of->ChemicalSubstance`, but by default we won't consider a NamedThing a Gene.
1. Normally we would contact the normalizer to get the category of a given ID but `NCBIGENE:18671` is not in the normalizer. I also tried `NCBIGene:18671` but that's not in there either. 
1. The automat/ctd Gene-affects_stability_of->ChemicalSubstance endpoint does not return any results when the node NCBIGene:18671 has category Gene. It only returns results for category NamedThing. This is going to cause issues if NCBIGene:18671 is added to the normalizer because we will ask that endpoint using category Gene.
1. The capitalization in automat/ctd for NCBIGENE:18671 does not match the capitalization in the `id_prefixes` property in the biolink model. This will also cause issues with this query.

I don't think Strider is doing anything wrong with this query. I'll close this for now but feel free to reach out if you think I  missed something.

**Comment by patrickkwang** [comment]
To follow up a little, shouldn't Strider be handling point 1 there? If the query graph asks for "NamedThing...", we should include "Gene..." in our query plan, right? Point 3 sounds like an automat/ctd issue. Points 2 and 4 are known inconsistencies that should hopefully resolve in the next month?

**Comment by cbizon** [comment]
Yeah, 2/3/4 are all problems with automat and nodenorm.  1 is something that I think strider should do.
